name: "Build"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: zer0lang
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix build . .#musl .#mingw --accept-flake-config

    - uses: actions/upload-artifact@v3
      with:
        name: x86_64-unknown-linux-gnu
        path: result/bin/main

    - uses: actions/upload-artifact@v3
      with:
        name: x86_64-unknown-linux-musl
        path: result-1/bin/main

    - uses: actions/upload-artifact@v3
      with:
        name: x86_64-w64-mingw32
        path: result-2/bin/main.exe


